call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'morhetz/gruvbox'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'preservim/tagbar'
Plug 'bagrat/vim-buffet'
Plug 'vim-airline/vim-airline'
Plug 'godlygeek/tabular'
Plug 'preservim/vim-markdown'
call plug#end()
